// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function AddRecentFile(arg1:string):Promise<void>;

export function BrowseFile():Promise<string>;

export function BrowseProjectFolder():Promise<string>;

export function DeleteFile(arg1:string):Promise<void>;

export function GetDefaultBrowseDir():Promise<string>;

export function GetRecentFiles():Promise<Array<main.RecentFile>>;

export function GetRecentProjects():Promise<Array<main.RecentProject>>;

export function Greet(arg1:string):Promise<string>;

export function ListFormatFiles(arg1:string):Promise<Array<string>>;

export function LogFrontendError(arg1:string):Promise<void>;

export function OpenProject(arg1:string):Promise<void>;

export function ReadExternalFile(arg1:string):Promise<string>;

export function ReadFile(arg1:string):Promise<string>;

export function WriteFile(arg1:string,arg2:string):Promise<void>;
