// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AddRecentFile(arg1) {
  return window['go']['main']['App']['AddRecentFile'](arg1);
}

export function BrowseFile() {
  return window['go']['main']['App']['BrowseFile']();
}

export function BrowseProjectFolder() {
  return window['go']['main']['App']['BrowseProjectFolder']();
}

export function CreateElement(arg1, arg2) {
  return window['go']['main']['App']['CreateElement'](arg1, arg2);
}

export function DeleteFile(arg1) {
  return window['go']['main']['App']['DeleteFile'](arg1);
}

export function GetDefaultBrowseDir() {
  return window['go']['main']['App']['GetDefaultBrowseDir']();
}

export function GetOtherExtensions() {
  return window['go']['main']['App']['GetOtherExtensions']();
}

export function GetRecentFiles() {
  return window['go']['main']['App']['GetRecentFiles']();
}

export function GetRecentProjects() {
  return window['go']['main']['App']['GetRecentProjects']();
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function ListAllFilesWithModTime() {
  return window['go']['main']['App']['ListAllFilesWithModTime']();
}

export function ListFormatFiles(arg1) {
  return window['go']['main']['App']['ListFormatFiles'](arg1);
}

export function ListOtherFileExtensions() {
  return window['go']['main']['App']['ListOtherFileExtensions']();
}

export function LogFrontendError(arg1) {
  return window['go']['main']['App']['LogFrontendError'](arg1);
}

export function OpenProject(arg1) {
  return window['go']['main']['App']['OpenProject'](arg1);
}

export function ReadExternalFile(arg1) {
  return window['go']['main']['App']['ReadExternalFile'](arg1);
}

export function ReadFile(arg1) {
  return window['go']['main']['App']['ReadFile'](arg1);
}

export function Reindex() {
  return window['go']['main']['App']['Reindex']();
}

export function RenameFile(arg1, arg2) {
  return window['go']['main']['App']['RenameFile'](arg1, arg2);
}

export function SetOtherExtensions(arg1) {
  return window['go']['main']['App']['SetOtherExtensions'](arg1);
}

export function WriteFile(arg1, arg2) {
  return window['go']['main']['App']['WriteFile'](arg1, arg2);
}
